spring:
  application:
    name: gearbox
  datasource:
    url: jdbc:postgresql://localhost:5455/gearbox
    username: developer
    password: comsystoreply
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  key: ${JWT_KEY}
  accessTokenExpiration: 3600000
  refreshTokenExpiration: 86400000